/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CloudConfigV1 : IEquatable<CloudConfigV1>
    { 
        /// <summary>
        /// Gets or Sets EndpointConfig
        /// </summary>
        [Required]

        [DataMember(Name="endpointConfig")]
        public CloudConfigV1EndpointConfig EndpointConfig { get; set; }

        /// <summary>
        /// Gets or Sets ManagementEventConfig
        /// </summary>

        [DataMember(Name="managementEventConfig")]
        public EventsConfigV1 ManagementEventConfig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CloudConfigV1 {\n");
            sb.Append("  EndpointConfig: ").Append(EndpointConfig).Append("\n");
            sb.Append("  ManagementEventConfig: ").Append(ManagementEventConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CloudConfigV1)obj);
        }

        /// <summary>
        /// Returns true if CloudConfigV1 instances are equal
        /// </summary>
        /// <param name="other">Instance of CloudConfigV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CloudConfigV1 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EndpointConfig == other.EndpointConfig ||
                    EndpointConfig != null &&
                    EndpointConfig.Equals(other.EndpointConfig)
                ) && 
                (
                    ManagementEventConfig == other.ManagementEventConfig ||
                    ManagementEventConfig != null &&
                    ManagementEventConfig.Equals(other.ManagementEventConfig)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EndpointConfig != null)
                    hashCode = hashCode * 59 + EndpointConfig.GetHashCode();
                    if (ManagementEventConfig != null)
                    hashCode = hashCode * 59 + ManagementEventConfig.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CloudConfigV1 left, CloudConfigV1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CloudConfigV1 left, CloudConfigV1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
