/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Configuration of the Command/Reponse Channel
    /// </summary>
    [DataContract]
    public partial class CommandResponseV1 : IEquatable<CommandResponseV1>
    { 
        /// <summary>
        /// Enables or Disables the Local REST Interface
        /// </summary>
        /// <value>Enables or Disables the Local REST Interface</value>
        [Required]

        [DataMember(Name="enableLocalRest")]
        public bool? EnableLocalRest { get; set; }

        /// <summary>
        /// Configuration of the Command/Response Channels
        /// </summary>
        /// <value>Configuration of the Command/Response Channels</value>

        [DataMember(Name="connections")]
        public List<CommandResponseV1Connections> Connections { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommandResponseV1 {\n");
            sb.Append("  EnableLocalRest: ").Append(EnableLocalRest).Append("\n");
            sb.Append("  Connections: ").Append(Connections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CommandResponseV1)obj);
        }

        /// <summary>
        /// Returns true if CommandResponseV1 instances are equal
        /// </summary>
        /// <param name="other">Instance of CommandResponseV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommandResponseV1 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EnableLocalRest == other.EnableLocalRest ||
                    EnableLocalRest != null &&
                    EnableLocalRest.Equals(other.EnableLocalRest)
                ) && 
                (
                    Connections == other.Connections ||
                    Connections != null &&
                    Connections.SequenceEqual(other.Connections)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EnableLocalRest != null)
                    hashCode = hashCode * 59 + EnableLocalRest.GetHashCode();
                    if (Connections != null)
                    hashCode = hashCode * 59 + Connections.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CommandResponseV1 left, CommandResponseV1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CommandResponseV1 left, CommandResponseV1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
