/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// System CPU Statistics
    /// </summary>
    [DataContract]
    public partial class CpuStats : IEquatable<CpuStats>
    { 
        /// <summary>
        /// User processes CPU utilization percentage
        /// </summary>
        /// <value>User processes CPU utilization percentage</value>
        [Required]

        [DataMember(Name="user")]
        public int? User { get; set; }

        /// <summary>
        /// System processes CPU utilization percentage
        /// </summary>
        /// <value>System processes CPU utilization percentage</value>
        [Required]

        [DataMember(Name="system")]
        public int? System { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CpuStats {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  System: ").Append(System).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CpuStats)obj);
        }

        /// <summary>
        /// Returns true if CpuStats instances are equal
        /// </summary>
        /// <param name="other">Instance of CpuStats to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CpuStats other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    User == other.User ||
                    User != null &&
                    User.Equals(other.User)
                ) && 
                (
                    System == other.System ||
                    System != null &&
                    System.Equals(other.System)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (User != null)
                    hashCode = hashCode * 59 + User.GetHashCode();
                    if (System != null)
                    hashCode = hashCode * 59 + System.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CpuStats left, CpuStats right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CpuStats left, CpuStats right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
