/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Refresh installed certificate
    /// </summary>
    [DataContract]
    public partial class DeleteCertificateCommandCopy : IEquatable<DeleteCertificateCommandCopy>
    { 
        /// <summary>
        /// certificate name
        /// </summary>
        /// <value>certificate name</value>
        [Required]

        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// certificate type
        /// </summary>
        /// <value>certificate type</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ClientEnum for client
            /// </summary>
            [EnumMember(Value = "client")]
            ClientEnum = 0,
            /// <summary>
            /// Enum ServerEnum for server
            /// </summary>
            [EnumMember(Value = "server")]
            ServerEnum = 1,
            /// <summary>
            /// Enum AppEnum for app
            /// </summary>
            [EnumMember(Value = "app")]
            AppEnum = 2        }

        /// <summary>
        /// certificate type
        /// </summary>
        /// <value>certificate type</value>
        [Required]

        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeleteCertificateCommandCopy {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DeleteCertificateCommandCopy)obj);
        }

        /// <summary>
        /// Returns true if DeleteCertificateCommandCopy instances are equal
        /// </summary>
        /// <param name="other">Instance of DeleteCertificateCommandCopy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeleteCertificateCommandCopy other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DeleteCertificateCommandCopy left, DeleteCertificateCommandCopy right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DeleteCertificateCommandCopy left, DeleteCertificateCommandCopy right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
