/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Retrive current GPO pin statuses
    /// </summary>
    [DataContract]
    public partial class GPOStatusResponse : IEquatable<GPOStatusResponse>
    { 
        /// <summary>
        /// Gets or Sets _1
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum Enum
        {
            /// <summary>
            /// Enum HIGHEnum for HIGH
            /// </summary>
            [EnumMember(Value = "HIGH")]
            HIGHEnum = 0,
            /// <summary>
            /// Enum LOWEnum for LOW
            /// </summary>
            [EnumMember(Value = "LOW")]
            LOWEnum = 1        }

        /// <summary>
        /// Gets or Sets _1
        /// </summary>
        [Required]

        [MinLength(1)]
        [DataMember(Name = "1")]
        public Enum? _1 { get; set; }

        [MinLength(1)]
        [DataMember(Name = "2")]
        public Enum? _2 { get; set; }

        [MinLength(1)]
        [DataMember(Name = "3")]
        public Enum? _3 { get; set; }

        [MinLength(1)]
        [DataMember(Name = "4")]
        public Enum? _4 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GPOStatusResponse {\n");
            sb.Append("  _1: ").Append(_1).Append("\n");
            sb.Append("  _2: ").Append(_2).Append("\n");
            sb.Append("  _3: ").Append(_3).Append("\n");
            sb.Append("  _4: ").Append(_4).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GPOStatusResponse)obj);
        }

        /// <summary>
        /// Returns true if GPOStatusResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GPOStatusResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GPOStatusResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    _1 == other._1 ||
                    _1 != null &&
                    _1.Equals(other._1)
                ) && 
                (
                    _2 == other._2 ||
                    _2 != null &&
                    _2.Equals(other._2)
                ) && 
                (
                    _3 == other._3 ||
                    _3 != null &&
                    _3.Equals(other._3)
                ) && 
                (
                    _4 == other._4 ||
                    _4 != null &&
                    _4.Equals(other._4)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (_1 != null)
                    hashCode = hashCode * 59 + _1.GetHashCode();
                    if (_2 != null)
                    hashCode = hashCode * 59 + _2.GetHashCode();
                    if (_3 != null)
                    hashCode = hashCode * 59 + _3.GetHashCode();
                    if (_4 != null)
                    hashCode = hashCode * 59 + _4.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GPOStatusResponse left, GPOStatusResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GPOStatusResponse left, GPOStatusResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
