/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Configuration of HTTP Post Security
    /// </summary>
    [DataContract]
    public partial class HttpPostSecurityV1 : IEquatable<HttpPostSecurityV1>
    { 
        /// <summary>
        /// Enables or Disabled verifying that the server cert is for the server to which the message is being posted
        /// </summary>
        /// <value>Enables or Disabled verifying that the server cert is for the server to which the message is being posted</value>
        [Required]

        [DataMember(Name="verifyPeer")]
        public bool? VerifyPeer { get; set; }

        /// <summary>
        /// Enable or Disable verifiying that host name in the certificate is valid for the host name to which messages are being posted
        /// </summary>
        /// <value>Enable or Disable verifiying that host name in the certificate is valid for the host name to which messages are being posted</value>
        [Required]

        [DataMember(Name="verifyHost")]
        public bool? VerifyHost { get; set; }

        /// <summary>
        /// Type of Authentication to use when posting message
        /// </summary>
        /// <value>Type of Authentication to use when posting message</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AuthenticationTypeEnum
        {
            /// <summary>
            /// Enum NONEEnum for NONE
            /// </summary>
            [EnumMember(Value = "NONE")]
            NONEEnum = 0,
            /// <summary>
            /// Enum BASICEnum for BASIC
            /// </summary>
            [EnumMember(Value = "BASIC")]
            BASICEnum = 1,
            /// <summary>
            /// Enum TLSClientEnum for TLS-Client
            /// </summary>
            [EnumMember(Value = "TLS-Client")]
            TLSClientEnum = 2        }

        /// <summary>
        /// Type of Authentication to use when posting message
        /// </summary>
        /// <value>Type of Authentication to use when posting message</value>
        [Required]

        [DataMember(Name="authenticationType")]
        public AuthenticationTypeEnum? AuthenticationType { get; set; }

        /// <summary>
        /// Configuration of the Authentication Options
        /// </summary>
        /// <value>Configuration of the Authentication Options</value>

        [DataMember(Name="authenticationOptions")]
        public OneOfhttpPostSecurityV1AuthenticationOptions AuthenticationOptions { get; set; }

        /// <summary>
        /// Path and file name of the CA Certificate
        /// </summary>
        /// <value>Path and file name of the CA Certificate</value>

        [DataMember(Name="CACertificateFileLocation")]
        public string CACertificateFileLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpPostSecurityV1 {\n");
            sb.Append("  VerifyPeer: ").Append(VerifyPeer).Append("\n");
            sb.Append("  VerifyHost: ").Append(VerifyHost).Append("\n");
            sb.Append("  AuthenticationType: ").Append(AuthenticationType).Append("\n");
            sb.Append("  AuthenticationOptions: ").Append(AuthenticationOptions).Append("\n");
            sb.Append("  CACertificateFileLocation: ").Append(CACertificateFileLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((HttpPostSecurityV1)obj);
        }

        /// <summary>
        /// Returns true if HttpPostSecurityV1 instances are equal
        /// </summary>
        /// <param name="other">Instance of HttpPostSecurityV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpPostSecurityV1 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VerifyPeer == other.VerifyPeer ||
                    VerifyPeer != null &&
                    VerifyPeer.Equals(other.VerifyPeer)
                ) && 
                (
                    VerifyHost == other.VerifyHost ||
                    VerifyHost != null &&
                    VerifyHost.Equals(other.VerifyHost)
                ) && 
                (
                    AuthenticationType == other.AuthenticationType ||
                    AuthenticationType != null &&
                    AuthenticationType.Equals(other.AuthenticationType)
                ) && 
                (
                    AuthenticationOptions == other.AuthenticationOptions ||
                    AuthenticationOptions != null &&
                    AuthenticationOptions.Equals(other.AuthenticationOptions)
                ) && 
                (
                    CACertificateFileLocation == other.CACertificateFileLocation ||
                    CACertificateFileLocation != null &&
                    CACertificateFileLocation.Equals(other.CACertificateFileLocation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VerifyPeer != null)
                    hashCode = hashCode * 59 + VerifyPeer.GetHashCode();
                    if (VerifyHost != null)
                    hashCode = hashCode * 59 + VerifyHost.GetHashCode();
                    if (AuthenticationType != null)
                    hashCode = hashCode * 59 + AuthenticationType.GetHashCode();
                    if (AuthenticationOptions != null)
                    hashCode = hashCode * 59 + AuthenticationOptions.GetHashCode();
                    if (CACertificateFileLocation != null)
                    hashCode = hashCode * 59 + CACertificateFileLocation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(HttpPostSecurityV1 left, HttpPostSecurityV1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(HttpPostSecurityV1 left, HttpPostSecurityV1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
