/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Configuration of HTTP Post
    /// </summary>
    [DataContract]
    public partial class HttpPostV1 : IEquatable<HttpPostV1>
    { 
        /// <summary>
        /// Destination URL to Post messages
        /// </summary>
        /// <value>Destination URL to Post messages</value>
        [Required]

        [DataMember(Name="URL")]
        public string URL { get; set; }

        /// <summary>
        /// Gets or Sets Security
        /// </summary>
        [Required]

        [DataMember(Name="security")]
        public HttpPostSecurityV1 Security { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpPostV1 {\n");
            sb.Append("  URL: ").Append(URL).Append("\n");
            sb.Append("  Security: ").Append(Security).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((HttpPostV1)obj);
        }

        /// <summary>
        /// Returns true if HttpPostV1 instances are equal
        /// </summary>
        /// <param name="other">Instance of HttpPostV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpPostV1 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    URL == other.URL ||
                    URL != null &&
                    URL.Equals(other.URL)
                ) && 
                (
                    Security == other.Security ||
                    Security != null &&
                    Security.Equals(other.Security)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (URL != null)
                    hashCode = hashCode * 59 + URL.GetHashCode();
                    if (Security != null)
                    hashCode = hashCode * 59 + Security.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(HttpPostV1 left, HttpPostV1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(HttpPostV1 left, HttpPostV1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
