/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Asynchronous management events configuration
    /// </summary>
    [DataContract]
    public partial class ManagementEventsConfiguration : IEquatable<ManagementEventsConfiguration>
    { 
        /// <summary>
        /// Gets or Sets Errors
        /// </summary>

        [DataMember(Name="errors")]
        public ManagementEventsConfigurationErrors Errors { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>

        [DataMember(Name="warnings")]
        public ManagementEventsConfigurationWarnings Warnings { get; set; }

        /// <summary>
        /// Gets or Sets Heartbeat
        /// </summary>

        [DataMember(Name="heartbeat")]
        public ManagementEventsConfigurationHeartbeat Heartbeat { get; set; }

        /// <summary>
        /// GPI Events
        /// </summary>
        /// <value>GPI Events</value>

        [DataMember(Name="gpiEvents")]
        public bool? GpiEvents { get; set; }

        /// <summary>
        /// asyncronous events from user applications 
        /// </summary>
        /// <value>asyncronous events from user applications </value>

        [DataMember(Name="userappEvents")]
        public bool? UserappEvents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManagementEventsConfiguration {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("  Heartbeat: ").Append(Heartbeat).Append("\n");
            sb.Append("  GpiEvents: ").Append(GpiEvents).Append("\n");
            sb.Append("  UserappEvents: ").Append(UserappEvents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ManagementEventsConfiguration)obj);
        }

        /// <summary>
        /// Returns true if ManagementEventsConfiguration instances are equal
        /// </summary>
        /// <param name="other">Instance of ManagementEventsConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManagementEventsConfiguration other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Errors == other.Errors ||
                    Errors != null &&
                    Errors.Equals(other.Errors)
                ) && 
                (
                    Warnings == other.Warnings ||
                    Warnings != null &&
                    Warnings.Equals(other.Warnings)
                ) && 
                (
                    Heartbeat == other.Heartbeat ||
                    Heartbeat != null &&
                    Heartbeat.Equals(other.Heartbeat)
                ) && 
                (
                    GpiEvents == other.GpiEvents ||
                    GpiEvents != null &&
                    GpiEvents.Equals(other.GpiEvents)
                ) && 
                (
                    UserappEvents == other.UserappEvents ||
                    UserappEvents != null &&
                    UserappEvents.Equals(other.UserappEvents)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Errors != null)
                    hashCode = hashCode * 59 + Errors.GetHashCode();
                    if (Warnings != null)
                    hashCode = hashCode * 59 + Warnings.GetHashCode();
                    if (Heartbeat != null)
                    hashCode = hashCode * 59 + Heartbeat.GetHashCode();
                    if (GpiEvents != null)
                    hashCode = hashCode * 59 + GpiEvents.GetHashCode();
                    if (UserappEvents != null)
                    hashCode = hashCode * 59 + UserappEvents.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ManagementEventsConfiguration left, ManagementEventsConfiguration right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ManagementEventsConfiguration left, ManagementEventsConfiguration right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
