/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Reader temperature warning limits
    /// </summary>
    [DataContract]
    public partial class ManagementEventsConfigurationWarningsTemperature : IEquatable<ManagementEventsConfigurationWarningsTemperature>
    { 
        /// <summary>
        /// Ambient temperature limit
        /// </summary>
        /// <value>Ambient temperature limit</value>
        [Required]

        [DataMember(Name="ambient")]
        public decimal? Ambient { get; set; }

        /// <summary>
        /// PA temperature limit
        /// </summary>
        /// <value>PA temperature limit</value>
        [Required]

        [DataMember(Name="pa")]
        public decimal? Pa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManagementEventsConfigurationWarningsTemperature {\n");
            sb.Append("  Ambient: ").Append(Ambient).Append("\n");
            sb.Append("  Pa: ").Append(Pa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ManagementEventsConfigurationWarningsTemperature)obj);
        }

        /// <summary>
        /// Returns true if ManagementEventsConfigurationWarningsTemperature instances are equal
        /// </summary>
        /// <param name="other">Instance of ManagementEventsConfigurationWarningsTemperature to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManagementEventsConfigurationWarningsTemperature other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Ambient == other.Ambient ||
                    Ambient != null &&
                    Ambient.Equals(other.Ambient)
                ) && 
                (
                    Pa == other.Pa ||
                    Pa != null &&
                    Pa.Equals(other.Pa)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Ambient != null)
                    hashCode = hashCode * 59 + Ambient.GetHashCode();
                    if (Pa != null)
                    hashCode = hashCode * 59 + Pa.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ManagementEventsConfigurationWarningsTemperature left, ManagementEventsConfigurationWarningsTemperature right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ManagementEventsConfigurationWarningsTemperature left, ManagementEventsConfigurationWarningsTemperature right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
