/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Gateway specific configuration
    /// </summary>
    [DataContract]
    public partial class ReaderConfigREADERGATEWAY : IEquatable<ReaderConfigREADERGATEWAY>
    { 
        /// <summary>
        /// Gets or Sets Retention
        /// </summary>

        [DataMember(Name="retention")]
        public TagDataEventsRetentionConfiguration Retention { get; set; }

        /// <summary>
        /// Gets or Sets Batching
        /// </summary>

        [DataMember(Name="batching")]
        public TagDataEventsBatchingConfiguration Batching { get; set; }

        /// <summary>
        /// Gets or Sets ManagementEventConfig
        /// </summary>

        [DataMember(Name="managementEventConfig")]
        public ManagementEventsConfiguration ManagementEventConfig { get; set; }

        /// <summary>
        /// Gets or Sets EndpointConfig
        /// </summary>

        [DataMember(Name="endpointConfig")]
        public ReaderConfigREADERGATEWAYEndpointConfig EndpointConfig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReaderConfigREADERGATEWAY {\n");
            sb.Append("  Retention: ").Append(Retention).Append("\n");
            sb.Append("  Batching: ").Append(Batching).Append("\n");
            sb.Append("  ManagementEventConfig: ").Append(ManagementEventConfig).Append("\n");
            sb.Append("  EndpointConfig: ").Append(EndpointConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ReaderConfigREADERGATEWAY)obj);
        }

        /// <summary>
        /// Returns true if ReaderConfigREADERGATEWAY instances are equal
        /// </summary>
        /// <param name="other">Instance of ReaderConfigREADERGATEWAY to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReaderConfigREADERGATEWAY other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Retention == other.Retention ||
                    Retention != null &&
                    Retention.Equals(other.Retention)
                ) && 
                (
                    Batching == other.Batching ||
                    Batching != null &&
                    Batching.Equals(other.Batching)
                ) && 
                (
                    ManagementEventConfig == other.ManagementEventConfig ||
                    ManagementEventConfig != null &&
                    ManagementEventConfig.Equals(other.ManagementEventConfig)
                ) && 
                (
                    EndpointConfig == other.EndpointConfig ||
                    EndpointConfig != null &&
                    EndpointConfig.Equals(other.EndpointConfig)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Retention != null)
                    hashCode = hashCode * 59 + Retention.GetHashCode();
                    if (Batching != null)
                    hashCode = hashCode * 59 + Batching.GetHashCode();
                    if (ManagementEventConfig != null)
                    hashCode = hashCode * 59 + ManagementEventConfig.GetHashCode();
                    if (EndpointConfig != null)
                    hashCode = hashCode * 59 + EndpointConfig.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ReaderConfigREADERGATEWAY left, ReaderConfigREADERGATEWAY right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ReaderConfigREADERGATEWAY left, ReaderConfigREADERGATEWAY right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
