/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// registration server security details
    /// </summary>
    [DataContract]
    public partial class RegistrationRegistrationSecurity : IEquatable<RegistrationRegistrationSecurity>
    { 
        /// <summary>
        /// verify server certificate
        /// </summary>
        /// <value>verify server certificate</value>

        [DataMember(Name="verifyPeer")]
        public bool? VerifyPeer { get; set; }

        /// <summary>
        /// verify server hosname
        /// </summary>
        /// <value>verify server hosname</value>

        [DataMember(Name="verifyHost")]
        public bool? VerifyHost { get; set; }

        /// <summary>
        /// CA certificate file content
        /// </summary>
        /// <value>CA certificate file content</value>

        [DataMember(Name="CACertificateFileContent")]
        public string CACertificateFileContent { get; set; }

        /// <summary>
        /// CA certificate file location
        /// </summary>
        /// <value>CA certificate file location</value>

        [DataMember(Name="CACertificateFileLocation")]
        public string CACertificateFileLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegistrationRegistrationSecurity {\n");
            sb.Append("  VerifyPeer: ").Append(VerifyPeer).Append("\n");
            sb.Append("  VerifyHost: ").Append(VerifyHost).Append("\n");
            sb.Append("  CACertificateFileContent: ").Append(CACertificateFileContent).Append("\n");
            sb.Append("  CACertificateFileLocation: ").Append(CACertificateFileLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RegistrationRegistrationSecurity)obj);
        }

        /// <summary>
        /// Returns true if RegistrationRegistrationSecurity instances are equal
        /// </summary>
        /// <param name="other">Instance of RegistrationRegistrationSecurity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegistrationRegistrationSecurity other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    VerifyPeer == other.VerifyPeer ||
                    VerifyPeer != null &&
                    VerifyPeer.Equals(other.VerifyPeer)
                ) && 
                (
                    VerifyHost == other.VerifyHost ||
                    VerifyHost != null &&
                    VerifyHost.Equals(other.VerifyHost)
                ) && 
                (
                    CACertificateFileContent == other.CACertificateFileContent ||
                    CACertificateFileContent != null &&
                    CACertificateFileContent.Equals(other.CACertificateFileContent)
                ) && 
                (
                    CACertificateFileLocation == other.CACertificateFileLocation ||
                    CACertificateFileLocation != null &&
                    CACertificateFileLocation.Equals(other.CACertificateFileLocation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (VerifyPeer != null)
                    hashCode = hashCode * 59 + VerifyPeer.GetHashCode();
                    if (VerifyHost != null)
                    hashCode = hashCode * 59 + VerifyHost.GetHashCode();
                    if (CACertificateFileContent != null)
                    hashCode = hashCode * 59 + CACertificateFileContent.GetHashCode();
                    if (CACertificateFileLocation != null)
                    hashCode = hashCode * 59 + CACertificateFileLocation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RegistrationRegistrationSecurity left, RegistrationRegistrationSecurity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RegistrationRegistrationSecurity left, RegistrationRegistrationSecurity right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
