/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Tag with RSSI below threshold will not be inventoried by the radio Note: Currently ONLY supported by the FX9600
    /// </summary>
    [DataContract]
    public partial class RssiFilter : IEquatable<RssiFilter>
    { 
        /// <summary>
        /// Threshold (in dbm) below which the radio will ignore a tag response
        /// </summary>
        /// <value>Threshold (in dbm) below which the radio will ignore a tag response</value>

        [Range(-128, -20)]
        [DataMember(Name="threshold")]
        public int? Threshold { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RssiFilter {\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RssiFilter)obj);
        }

        /// <summary>
        /// Returns true if RssiFilter instances are equal
        /// </summary>
        /// <param name="other">Instance of RssiFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RssiFilter other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Threshold == other.Threshold ||
                    Threshold != null &&
                    Threshold.Equals(other.Threshold)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Threshold != null)
                    hashCode = hashCode * 59 + Threshold.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RssiFilter left, RssiFilter right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RssiFilter left, RssiFilter right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
