/*
 * RAW MQTT Payloads
 *
 *  
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Changes logging level
    /// </summary>
    [DataContract]
    public partial class SetLogsCommand : IEquatable<SetLogsCommand>
    { 
        /// <summary>
        /// Gets or Sets RadioPacketLog
        /// </summary>

        [DataMember(Name="radioPacketLog")]
        public bool? RadioPacketLog { get; set; }

        /// <summary>
        /// Gets or Sets Components
        /// </summary>

        [DataMember(Name="components")]
        public List<SetLogsCommandComponents> Components { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetLogsCommand {\n");
            sb.Append("  RadioPacketLog: ").Append(RadioPacketLog).Append("\n");
            sb.Append("  Components: ").Append(Components).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SetLogsCommand)obj);
        }

        /// <summary>
        /// Returns true if SetLogsCommand instances are equal
        /// </summary>
        /// <param name="other">Instance of SetLogsCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetLogsCommand other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RadioPacketLog == other.RadioPacketLog ||
                    RadioPacketLog != null &&
                    RadioPacketLog.Equals(other.RadioPacketLog)
                ) && 
                (
                    Components == other.Components ||
                    Components != null &&
                    Components.SequenceEqual(other.Components)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RadioPacketLog != null)
                    hashCode = hashCode * 59 + RadioPacketLog.GetHashCode();
                    if (Components != null)
                    hashCode = hashCode * 59 + Components.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SetLogsCommand left, SetLogsCommand right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SetLogsCommand left, SetLogsCommand right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
