//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraIoTConnector.Persistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZebraIoTConnector.Persistence.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [ZebraRFID_DockDoor]
        ///GO
        ///SET IDENTITY_INSERT[dbo].[StorageUnits] ON
        ///GO
        ///INSERT[dbo].[StorageUnits]([Id], [Name], [Description], [Direction]) VALUES(1, N&apos;DOCK_OUT_WH1&apos;, N&apos;DockDoor_Warehouse1&apos;, 2)
        ///GO
        ///INSERT[dbo].[StorageUnits] ([Id], [Name], [Description], [Direction]) VALUES(2, N&apos;DOCK_IN_WH2&apos;, N&apos;DockDoor_Warehouse2&apos;, 1)
        ///GO
        ///INSERT[dbo].[StorageUnits] ([Id], [Name], [Description], [Direction]) VALUES(3, N&apos;TRUCK&apos;, N&apos;TRUCK&apos;, 1)
        ///GO
        ///SET IDENTITY_INSERT[dbo].[StorageUnits] OFF
        ///GO
        ///SET IDENTITY_INSERT[d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitScript {
            get {
                return ResourceManager.GetString("InitScript", resourceCulture);
            }
        }
    }
}
